CREATE TABLE IF NOT EXISTS ticket (
	id int(10) NOT NULL AUTO_INCREMENT,
	fecha datetime NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS cliente (
	id int(10) NOT NULL AUTO_INCREMENT,
	nombre varchar(64) NOT NULL UNIQUE,
	PRIMARY KEY (id)
);

#INSERT INTO ticket VALUES(1, '2010-10-10 01:02:03');
#INSERT INTO ticket VALUES(2, '2011-11-11 01:02:03');

INSERT INTO cliente VALUES(1, 'javi');
INSERT INTO cliente VALUES(2, 'george');
